# Generated by Django 5.0 on 2024-05-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_remove_flight_destination_remove_flight_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
