# Generated by Django 5.0 on 2024-05-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_alter_flight_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destination',
            new_name='Destination',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='origin',
            new_name='Origin',
        ),
    ]
